# Heavily borrowed from https://superface.ai/blog/npm-publish-gh-actions-changelog

name: Release package

on:
  workflow_dispatch:
    inputs:
      release-type:
        description: 'Which type of release to generate?'
        type: choice
        required: true
        options: [patch, minor, major, prepatch, preminor, premajor, prerelease]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # Checkout project repository
      - name: Checkout
        uses: actions/checkout@v3


